CREATE TABLE market_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    price NUMERIC(30, 8) NOT NULL,
    price_change NUMERIC(30, 8),
    price_change_percent NUMERIC(19, 6),
    market_cap NUMERIC(30, 2),
    currency VARCHAR(3),
    quote_timestamp TIMESTAMPTZ NOT NULL,
    retrieved_at TIMESTAMPTZ NOT NULL,
    provider_name VARCHAR(64) NOT NULL,
    raw_data_json JSONB,
    CONSTRAINT fk_market_snapshot_company
        FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE RESTRICT,
    CONSTRAINT ck_market_snapshot_price_positive CHECK (price > 0),
    CONSTRAINT ck_market_snapshot_market_cap_nonnegative
        CHECK (market_cap IS NULL OR market_cap >= 0),
    CONSTRAINT ck_market_snapshot_currency
        CHECK (currency IS NULL OR currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_market_snapshot_provider_not_blank CHECK (btrim(provider_name) <> '')
);
