CREATE TABLE financial_metric_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    pe_ttm NUMERIC(30, 12),
    forward_pe NUMERIC(30, 12),
    peg_ratio NUMERIC(30, 12),
    price_to_sales NUMERIC(30, 12),
    revenue_ttm NUMERIC(30, 2),
    gross_margin NUMERIC(30, 12),
    net_margin NUMERIC(30, 12),
    return_on_equity NUMERIC(30, 12),
    revenue_growth NUMERIC(30, 12),
    earnings_growth NUMERIC(30, 12),
    debt_to_equity NUMERIC(30, 12),
    current_ratio NUMERIC(30, 12),
    beta NUMERIC(30, 12),
    currency VARCHAR(3),
    reported_at DATE,
    retrieved_at TIMESTAMPTZ NOT NULL,
    provider_name VARCHAR(64) NOT NULL,
    raw_data_json JSONB,
    CONSTRAINT fk_financial_metric_snapshot_company
        FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE RESTRICT,
    CONSTRAINT ck_financial_metric_snapshot_currency
        CHECK (currency IS NULL OR currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_financial_metric_snapshot_provider_not_blank
        CHECK (btrim(provider_name) <> '')
);
