CREATE TABLE historical_price (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    trading_date DATE NOT NULL,
    open_price NUMERIC(30, 8),
    high_price NUMERIC(30, 8),
    low_price NUMERIC(30, 8),
    close_price NUMERIC(30, 8) NOT NULL,
    adjusted_close NUMERIC(30, 8),
    volume BIGINT,
    currency VARCHAR(3),
    provider_name VARCHAR(64) NOT NULL,
    retrieved_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_historical_price_company
        FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE RESTRICT,
    CONSTRAINT uk_historical_price_company_date_provider
        UNIQUE (company_id, trading_date, provider_name),
    CONSTRAINT ck_historical_price_open_positive
        CHECK (open_price IS NULL OR open_price > 0),
    CONSTRAINT ck_historical_price_high_positive
        CHECK (high_price IS NULL OR high_price > 0),
    CONSTRAINT ck_historical_price_low_positive
        CHECK (low_price IS NULL OR low_price > 0),
    CONSTRAINT ck_historical_price_close_positive CHECK (close_price > 0),
    CONSTRAINT ck_historical_price_adjusted_close_positive
        CHECK (adjusted_close IS NULL OR adjusted_close > 0),
    CONSTRAINT ck_historical_price_volume_nonnegative
        CHECK (volume IS NULL OR volume >= 0),
    CONSTRAINT ck_historical_price_currency
        CHECK (currency IS NULL OR currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_historical_price_provider_not_blank
        CHECK (btrim(provider_name) <> '')
);
