CREATE TABLE news_article (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(255),
    headline VARCHAR(1000) NOT NULL,
    source_name VARCHAR(255),
    article_url VARCHAR(2048) NOT NULL,
    description TEXT,
    published_at TIMESTAMPTZ NOT NULL,
    retrieved_at TIMESTAMPTZ NOT NULL,
    url_hash VARCHAR(64) NOT NULL,
    provider_name VARCHAR(64) NOT NULL,
    CONSTRAINT uk_news_article_url_hash UNIQUE (url_hash),
    CONSTRAINT ck_news_article_headline_not_blank CHECK (btrim(headline) <> ''),
    CONSTRAINT ck_news_article_source_not_blank
        CHECK (source_name IS NULL OR btrim(source_name) <> ''),
    CONSTRAINT ck_news_article_url_not_blank CHECK (btrim(article_url) <> ''),
    CONSTRAINT ck_news_article_provider_not_blank CHECK (btrim(provider_name) <> ''),
    CONSTRAINT ck_news_article_url_hash_format CHECK (url_hash ~ '^[0-9a-f]{64}$')
);

CREATE UNIQUE INDEX uk_news_article_provider_external_id
    ON news_article (provider_name, external_id)
    WHERE external_id IS NOT NULL;

CREATE INDEX idx_news_article_published_at
    ON news_article (published_at DESC, id DESC);

CREATE TABLE news_article_company (
    news_article_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    CONSTRAINT pk_news_article_company PRIMARY KEY (news_article_id, company_id),
    CONSTRAINT fk_news_article_company_article
        FOREIGN KEY (news_article_id) REFERENCES news_article (id) ON DELETE CASCADE,
    CONSTRAINT fk_news_article_company_company
        FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE
);

CREATE INDEX idx_news_article_company_company
    ON news_article_company (company_id, news_article_id);
