CREATE TABLE comparison_brief (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    left_company_id BIGINT NOT NULL,
    right_company_id BIGINT NOT NULL,
    overall_summary TEXT NOT NULL,
    advantages_json JSONB NOT NULL,
    key_risks_json JSONB NOT NULL,
    model_name VARCHAR(255) NOT NULL,
    prompt_version VARCHAR(128) NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL,
    data_cutoff_at TIMESTAMPTZ NOT NULL,
    input_hash VARCHAR(64) NOT NULL,
    CONSTRAINT fk_comparison_brief_left_company
        FOREIGN KEY (left_company_id) REFERENCES company (id) ON DELETE RESTRICT,
    CONSTRAINT fk_comparison_brief_right_company
        FOREIGN KEY (right_company_id) REFERENCES company (id) ON DELETE RESTRICT,
    CONSTRAINT ck_comparison_brief_distinct_companies
        CHECK (left_company_id <> right_company_id),
    CONSTRAINT ck_comparison_brief_summary_not_blank CHECK (btrim(overall_summary) <> ''),
    CONSTRAINT ck_comparison_brief_model_not_blank CHECK (btrim(model_name) <> ''),
    CONSTRAINT ck_comparison_brief_prompt_not_blank CHECK (btrim(prompt_version) <> ''),
    CONSTRAINT ck_comparison_brief_hash_format CHECK (input_hash ~ '^[0-9a-f]{64}$')
);

CREATE INDEX idx_comparison_brief_pair ON comparison_brief (left_company_id, right_company_id);
CREATE INDEX idx_comparison_brief_generated_at ON comparison_brief (generated_at DESC);
CREATE INDEX idx_comparison_brief_input_hash ON comparison_brief (input_hash);

CREATE TABLE comparison_brief_source (
    comparison_brief_id BIGINT NOT NULL,
    source_type VARCHAR(64) NOT NULL,
    source_reference VARCHAR(32) NOT NULL,
    news_article_id BIGINT,
    financial_snapshot_id BIGINT,
    market_snapshot_id BIGINT,
    CONSTRAINT pk_comparison_brief_source PRIMARY KEY (comparison_brief_id, source_reference),
    CONSTRAINT fk_comparison_brief_source_brief
        FOREIGN KEY (comparison_brief_id) REFERENCES comparison_brief (id) ON DELETE CASCADE,
    CONSTRAINT fk_comparison_brief_source_news
        FOREIGN KEY (news_article_id) REFERENCES news_article (id) ON DELETE RESTRICT,
    CONSTRAINT fk_comparison_brief_source_financial
        FOREIGN KEY (financial_snapshot_id) REFERENCES financial_metric_snapshot (id) ON DELETE RESTRICT,
    CONSTRAINT fk_comparison_brief_source_market
        FOREIGN KEY (market_snapshot_id) REFERENCES market_snapshot (id) ON DELETE RESTRICT,
    CONSTRAINT ck_comparison_brief_source_type_not_blank CHECK (btrim(source_type) <> ''),
    CONSTRAINT ck_comparison_brief_source_reference_not_blank CHECK (btrim(source_reference) <> '')
);

CREATE INDEX idx_comparison_brief_source_brief ON comparison_brief_source (comparison_brief_id);
