CREATE TABLE news_retrieval (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    retrieved_at TIMESTAMPTZ NOT NULL,
    result_count INTEGER NOT NULL,
    provider_name VARCHAR(64) NOT NULL,
    CONSTRAINT fk_news_retrieval_company FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE,
    CONSTRAINT ck_news_retrieval_count_nonnegative CHECK (result_count >= 0),
    CONSTRAINT ck_news_retrieval_provider_not_blank CHECK (btrim(provider_name) <> '')
);
CREATE INDEX idx_news_retrieval_company_retrieved ON news_retrieval (company_id, retrieved_at DESC, id DESC);
