import type { ComparisonDashboard } from '../features/comparison/types/comparison.ts'

export function comparisonFixture(): ComparisonDashboard {
  return {
    comparisonId: 'AAPL:MSFT:1Y:RETURN',
    left: {
      ticker: 'AAPL',
      companyName: 'Apple Inc.',
      exchange: 'NASDAQ',
      sector: 'Technology',
      industry: 'Consumer Electronics',
      country: 'US',
      website: 'https://www.apple.com',
      logoUrl: null,
      description: 'Apple designs and markets consumer technology products.',
      price: 192.62,
      priceChange: 1.35,
      priceChangePercent: 0.71,
      marketCap: 2_960_000_000_000,
      currency: 'USD',
      quoteTimestamp: '2026-07-19T20:00:00Z',
      peTtm: 28.74,
      revenueTtm: 394_330_000_000,
      companyUpdatedAt: '2026-07-19T20:01:00Z',
      marketRetrievedAt: '2026-07-19T20:02:00Z',
      metricsRetrievedAt: '2026-07-19T20:03:00Z',
    },
    right: {
      ticker: 'MSFT',
      companyName: 'Microsoft Corporation',
      exchange: 'NASDAQ',
      sector: 'Technology',
      industry: 'Software',
      country: 'US',
      website: 'https://www.microsoft.com',
      logoUrl: null,
      description: 'Microsoft develops software, cloud services, and devices.',
      price: 417.11,
      priceChange: -0.92,
      priceChangePercent: -0.22,
      marketCap: 3_100_000_000_000,
      currency: 'USD',
      quoteTimestamp: '2026-07-19T20:00:00Z',
      peTtm: 33.21,
      revenueTtm: 245_120_000_000,
      companyUpdatedAt: '2026-07-19T20:01:00Z',
      marketRetrievedAt: '2026-07-19T20:02:00Z',
      metricsRetrievedAt: '2026-07-19T20:03:00Z',
    },
    pricePerformance: {
      period: '1Y',
      mode: 'RETURN',
      startDate: '2026-07-17',
      endDate: '2026-07-19',
      pointCount: 3,
      leftReturnPercent: 18.4,
      rightReturnPercent: -7.2,
      leftCurrency: 'USD',
      rightCurrency: 'USD',
      series: [
        { date: '2026-07-17', leftValue: 0, rightValue: 0 },
        { date: '2026-07-18', leftValue: 8.2, rightValue: -2.1 },
        { date: '2026-07-19', leftValue: 18.4, rightValue: -7.2 },
      ],
    },
    metricGroups: [
      {
        category: 'VALUATION',
        metrics: [{
          code: 'PE_TTM',
          displayName: 'P/E (TTM)',
          category: 'VALUATION',
          unit: 'RATIO',
          leftValue: 28.74,
          rightValue: 33.21,
          comparisonStrategy: 'CONTEXT_DEPENDENT',
          outcome: 'NEUTRAL',
          explanation: 'Valuation requires context.',
        }],
      },
      {
        category: 'PROFITABILITY',
        metrics: [{
          code: 'GROSS_MARGIN',
          displayName: 'Gross Margin',
          category: 'PROFITABILITY',
          unit: 'DECIMAL_FRACTION_PERCENT',
          leftValue: 0.459,
          rightValue: 0.692,
          comparisonStrategy: 'HIGHER_IS_GENERALLY_BETTER',
          outcome: 'RIGHT',
          explanation: 'MSFT has the higher supplied gross margin.',
        }],
      },
      {
        category: 'GROWTH',
        metrics: [{
          code: 'REVENUE_GROWTH',
          displayName: 'Revenue Growth',
          category: 'GROWTH',
          unit: 'DECIMAL_FRACTION_PERCENT',
          leftValue: null,
          rightValue: 0.146,
          comparisonStrategy: 'HIGHER_IS_GENERALLY_BETTER',
          outcome: 'INSUFFICIENT_DATA',
          explanation: 'A value is missing.',
        }],
      },
      {
        category: 'FINANCIAL_HEALTH',
        metrics: [{
          code: 'DEBT_TO_EQUITY',
          displayName: 'Debt-to-Equity',
          category: 'FINANCIAL_HEALTH',
          unit: 'RATIO',
          leftValue: 1.73,
          rightValue: 0.57,
          comparisonStrategy: 'LOWER_IS_GENERALLY_BETTER',
          outcome: 'RIGHT',
          explanation: 'MSFT has the lower supplied debt-to-equity ratio.',
        }],
      },
    ],
    news: {
      left: [{
        id: 1,
        headline: 'Apple announces new accessibility features',
        sourceName: 'Example News',
        url: 'https://example.com/apple',
        publishedAt: '2026-07-19T12:00:00Z',
        description: 'New product accessibility capabilities were announced.',
        relatedSymbols: ['AAPL'],
      }],
      right: [{
        id: 2,
        headline: 'Microsoft expands cloud region',
        sourceName: 'Example Wire',
        url: 'https://example.com/microsoft',
        publishedAt: '2026-07-18T12:00:00Z',
        description: null,
        relatedSymbols: ['MSFT'],
      }],
    },
    aiBrief: null,
    provenance: {
      financialProvider: 'FMP',
      newsProvider: 'YAHOO_FINANCE',
      leftCompanyUpdatedAt: '2026-07-19T20:01:00Z',
      rightCompanyUpdatedAt: '2026-07-19T20:01:00Z',
      leftMarketRetrievedAt: '2026-07-19T20:02:00Z',
      rightMarketRetrievedAt: '2026-07-19T20:02:00Z',
      leftMetricsRetrievedAt: '2026-07-19T20:03:00Z',
      rightMetricsRetrievedAt: '2026-07-19T20:03:00Z',
      leftHistoryRetrievedAt: '2026-07-19T20:04:00Z',
      rightHistoryRetrievedAt: '2026-07-19T20:04:00Z',
      leftNewsRetrievedAt: '2026-07-19T20:05:00Z',
      rightNewsRetrievedAt: '2026-07-19T20:05:00Z',
      historyStartDate: '2026-07-17',
      historyEndDate: '2026-07-19',
      lastUpdatedAt: '2026-07-19T20:05:00Z',
      cached: false,
    },
    warnings: [],
  }
}
